## R programming Assignment 2: Lexical scoping & cacheing functions
## that may require a long computation time
## Utilize two functions: 
## makeCacheMatrix which stores a matrix & its' inverse; 
## cacheSolve which computes the inverse of a matrix if not done so already.
## cacheSolve will only operate if makeCacheMatrix has 1st.
# Start:
## makeCacheMatrix function creates a 'special' matrix, 'environment', 'object', etc.
## It can cache inputed matrices and its' inverse (computed by cacheSolve below).
      makeCacheMatrix <- function(x = matrix()) {
## Setup an inverse cache 'm' to null when cacheMatrix runs.
      m <- NULL
## get the value of the uninverted matrix to the cache.
      get <- function() x
## setinverse from cacheSolve
      setinverse <- function(inverse)
## enivironment assigned the value 'm'
      m <<- inverse
## when called, the getinverse will either print NULL
## (when cacheSolve hasn't been run) OR will render the inverse of matrix.
      getinverse <- function() m
## "x" see x$setinverse() in cacheSolve code below.
#
## makeCachematrix finally returns a list of all nested functions
## so that they can be called.
  list(get = get, setinverse = setinverse, getinverse = getinverse)
  }
## cacheSolve is a function that calculates and caches the inverse of a matrix.
## cacheSolve caches the inverse of the matrix in the environment generated by
## makeCacheMatrix. After cacheSolve has calculated the inverse of a matrix once,
## it will retrieve the inverse from cache instead of calculating it over again.
  cacheSolve <- function(x, ...) {
## retreives a value from the cache for the inverse in makeCacheMatrix and
## assigns it to 'm'
      m <- x$getinverse()
## if m is not NULL, cacheSolve has already run
## and has saved the inverse in the makeCacheMatrix
## checks to see whether or not 'm' is NULL
      if(!is.null(m)) { 
      message("getting cached data")
## returns the cached inverse of matrix 'x'
      return(m)
## otherwise, if 'm' is NULL
  }
    else
## matrix 'x' will be retrieved using the get() function in the makeCacheMatrix environment.
      data <- x$get()
## and its' inverse will be computed
      m <- solve(data, ...)
## and assigned to cache in the makeCacheMatrix environment
      x$setinverse(m)
## returns the inverse of matrix 'x'
      return(m)
  }
  